/*DBTYPE:SQLSERVER|TARGETDB:HPFSIDS*/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'DIMN.PP_ASSET_STATUS_02'))
BEGIN
	DROP VIEW DIMN.PP_ASSET_STATUS_02
END
GO

CREATE VIEW DIMN.PP_ASSET_STATUS_02
AS
	SELECT 
		ASET_STAT_ID AS AssetStatusId,
		ASET_STAT_CDE AS AssetStatusCode,
		ASET_STAT_NM AS AssetStatusName,
		AGMT_TYP_CDE AS AgreementTypeCode,
		AGMT_TYP_NM AS AgreementTypeName
	FROM
		DIMN_20210430.ASET_STAT
	WHERE
		ASET_STAT_CDE NOT IN('AD','TX')
GO

GRANT SELECT ON DIMN.PP_ASSET_STATUS_02 TO DMUsr01
GO