/*DBTYPE:SQLSERVER|TARGETDB:HPFSIDS*/
IF EXISTS(SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'DIMN.PP_EXPIRED_ASSET_COUNT_01'))
	BEGIN
		DROP VIEW DIMN.PP_EXPIRED_ASSET_COUNT_01;
	END
GO

CREATE VIEW DIMN.PP_EXPIRED_ASSET_COUNT_01
WITH SCHEMABINDING
AS

SELECT
	PP.CombinationId,
	COUNT_BIG(*) as AssetCount
FROM FCT_20210430.PP_ASSET_DETAILS PP WITH(NOLOCK) 
WHERE
	PP.AgreementTypeCode = 'STL'
	AND PP.AgreementEndDate < getdate()
	AND (PP.AssetStatusName = 'Active')
	AND (PP.ParentAssetKey is null)
GROUP BY PP.CombinationId

GO

GRANT SELECT ON DIMN.PP_EXPIRED_ASSET_COUNT_01 TO DMUsr01
GO